In [8]:
import numpy as np
# 1 to 10
arr1 = np.arange(1,11)
print("range from 1 to 10",arr1)

#zeros 3x3
zeros = np.zeros((3,3))
print("zeros 3x3\n",zeros)
# ones 2x4
ones = np.ones((2, 4))
print("ones 2x4\n",ones)

range from 1 to 10 [ 1  2  3  4  5  6  7  8  9 10]
zeros 3x3
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones 2x4
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
#basic operations
import numpy as np
arr = np.array([2,4,6,8])
print("Sum:", np.sum(arr))
print("Mean:",np.mean(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))

Sum: 20
Mean: 5.0
Max: 8
Min: 2


In [16]:
#indexing and slicing
import numpy as np
arr = np.array([10,20,30,40,50])
print("First:",arr[0])
print("Last:",arr[-1])
print("Slice:",arr[1:4])

First: 10
Last: 50
Slice: [20 30 40]


In [ ]:
#Element-wise Operations
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Addition:",a+b)
print("Multiplication:",a*b)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [23]:
#Reshape Practice
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("matrix 2x3\n",arr.reshape(2,3))
print("matrix 3x2\n",arr.reshape(3,2))

matrix 2x3
 [[1 2 3]
 [4 5 6]]
matrix 3x2
 [[1 2]
 [3 4]
 [5 6]]


In [24]:
#Even Numbers
import numpy as np
arr = np.array([1,2,3,4,5,6])
even = arr[arr % 2 == 0]
print(even)

[2 4 6]


In [25]:
#Replace Values (>3 → 0)
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr[arr > 3] = 0
print(arr)

[1 2 3 0 0 0]


In [27]:
#Generate Random Numbers
import numpy as np
arr = np.random.rand(5)
print(arr)


[0.58910051 0.96504215 0.67585186 0.70717952 0.75375136]


In [29]:
#Matrix Operations
import numpy as np
arr = np.array([[1,2],[3,4]])
print("Total Sum:",np.sum(arr))
print("Row-wise Sum:", np.sum(arr, axis=1))


Total Sum: 10
Row-wise Sum: [3 7]


In [32]:
#challeng
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

# Multiply by 5
print("Multiply by 5",arr * 5)

# Elements > 25
print("Elements > 25",arr[arr > 25])

# Replace >25 with -1
arr[arr > 25] = -1
print("Replace >25 with -1",arr)

Multiply by 5 [ 50 100 150 200 250]
Elements > 25 [30 40 50]
Replace >25 with -1 [10 20 -1 -1 -1]
